name: CI Smoke Test

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Baseline smoke load
        run: |
          . venv/bin/activate
          python - <<'PY'
import joblib
obj = joblib.load('outputs/baseline_model.pkl')
print('Baseline artifact type:', type(obj).__name__)
PY

      - name: Lint quick_infer.py import
        run: |
          . venv/bin/activate
          python -c "import scripts.quick_infer as qi; print('quick_infer imported')"

      - name: Verify repo size is under limit (no large artifacts)
        run: |
          # Ensure no >100MB files are tracked in git
          ! git ls-files -z | xargs -0 -I{} bash -c 'test -f {} && [ $(wc -c < {} ) -le 100000000 ] || (echo "Large file tracked: {}" && exit 1)'


